using ETS2LA.Game.Output;

namespace Godspeed.Shared;

// SCSControls ABI v1: explicit field order and byte widths. A reflection-order
// change must never silently move gear or pedal commands in shared memory.
public static class SCSControlsLayout
{
    public const int Version = 1;
    public const int Size = 342;
    public const int GearUpOffset = 265;
    public const int GearDownOffset = 266;
    public const int Gear1Offset = 298;

    private static readonly (string Name, int Width)[] Fields =
    [
        ("j_left", 4),
        ("j_right", 4),
        ("j_up", 4),
        ("j_down", 4),
        ("selectfcs", 1),
        ("back", 1),
        ("skip", 1),
        ("scrol_up", 1),
        ("scrol_dwn", 1),
        ("mapzoom_in", 1),
        ("mapzoom_out", 1),
        ("trs_zoom_in", 1),
        ("trs_zoom_out", 1),
        ("joy_nav_prv", 1),
        ("joy_nav_nxt", 1),
        ("joy_sec_prv", 1),
        ("joy_sec_nxt", 1),
        ("scroll_j_x", 4),
        ("scroll_j_y", 4),
        ("shortcut_1", 1),
        ("shortcut_2", 1),
        ("shortcut_3", 1),
        ("shortcut_4", 1),
        ("pause", 1),
        ("screenshot", 1),
        ("cam1", 1),
        ("cam2", 1),
        ("cam3", 1),
        ("cam4", 1),
        ("cam5", 1),
        ("cam6", 1),
        ("cam7", 1),
        ("cam8", 1),
        ("camcycle", 1),
        ("camreset", 1),
        ("camrotate", 1),
        ("camzoomin", 1),
        ("camzoomout", 1),
        ("camzoom", 1),
        ("camfwd", 1),
        ("camback", 1),
        ("camleft", 1),
        ("camright", 1),
        ("camup", 1),
        ("camdown", 1),
        ("lookleft", 1),
        ("lookright", 1),
        ("camlr", 1),
        ("camud", 1),
        ("j_cam_lk_lr", 4),
        ("j_cam_lk_ud", 4),
        ("j_cam_mv_lr", 4),
        ("j_cam_mv_ud", 4),
        ("j_trzoom_in", 4),
        ("j_trzoom_out", 4),
        ("j_mappan_x", 4),
        ("j_mappan_y", 4),
        ("j_mapzom_in", 4),
        ("j_mapzom_out", 4),
        ("lookpos1", 1),
        ("lookpos2", 1),
        ("lookpos3", 1),
        ("lookpos4", 1),
        ("lookpos5", 1),
        ("lookpos6", 1),
        ("lookpos7", 1),
        ("lookpos8", 1),
        ("lookpos9", 1),
        ("looksteer", 1),
        ("lookblink", 1),
        ("steering", 4),
        ("aforward", 4),
        ("abackward", 4),
        ("clutch", 4),
        ("activate", 1),
        ("menu", 1),
        ("ignitionoff", 1),
        ("ignitionon", 1),
        ("ignitionstrt", 1),
        ("attach", 1),
        ("frontsuspup", 1),
        ("frontsuspdwn", 1),
        ("rearsuspup", 1),
        ("rearsuspdwn", 1),
        ("suspreset", 1),
        ("horn", 1),
        ("airhorn", 1),
        ("lighthorn", 1),
        ("beacon", 1),
        ("motorbrake", 1),
        ("engbraketog", 1),
        ("engbrakeup", 1),
        ("engbrakedwn", 1),
        ("trailerbrake", 1),
        ("retarderup", 1),
        ("retarderdown", 1),
        ("retarder0", 1),
        ("retarder1", 1),
        ("retarder2", 1),
        ("retarder3", 1),
        ("retarder4", 1),
        ("retarder5", 1),
        ("liftaxle", 1),
        ("liftaxlet", 1),
        ("slideaxlefwd", 1),
        ("slideaxlebwd", 1),
        ("slideaxleman", 1),
        ("diflock", 1),
        ("rwinopen", 1),
        ("rwinclose", 1),
        ("lwinopen", 1),
        ("lwinclose", 1),
        ("engbrakeauto", 1),
        ("retarderauto", 1),
        ("embrake", 1),
        ("laneassmode", 1),
        ("tranpwrmode", 1),
        ("parkingbrake", 1),
        ("wipers", 1),
        ("wipersback", 1),
        ("wipers0", 1),
        ("wipers1", 1),
        ("wipers2", 1),
        ("wipers3", 1),
        ("wipers4", 1),
        ("cruiectrl", 1),
        ("cruiectrlinc", 1),
        ("cruiectrldec", 1),
        ("cruiectrlres", 1),
        ("accmode", 1),
        ("laneassist", 1),
        ("light", 1),
        ("lightoff", 1),
        ("lightpark", 1),
        ("lighton", 1),
        ("hblight", 1),
        ("lblinker", 1),
        ("lblinkerh", 1),
        ("rblinker", 1),
        ("rblinkerh", 1),
        ("flasher4way", 1),
        ("showmirrors", 1),
        ("showhud", 1),
        ("navmap", 1),
        ("photo_mode", 1),
        ("quicksave", 1),
        ("quickload", 1),
        ("radio", 1),
        ("radionext", 1),
        ("radioprev", 1),
        ("radioup", 1),
        ("radiodown", 1),
        ("display", 1),
        ("quickpark", 1),
        ("dashmapzoom", 1),
        ("tripreset", 1),
        ("sb_activate", 1),
        ("sb_swap", 1),
        ("infotainment", 1),
        ("photores", 1),
        ("photomove", 1),
        ("phototake", 1),
        ("photofwd", 1),
        ("photobwd", 1),
        ("photoleft", 1),
        ("photoright", 1),
        ("photoup", 1),
        ("photodown", 1),
        ("photorolll", 1),
        ("photorollr", 1),
        ("photosman", 1),
        ("photo_opts", 1),
        ("photosnap", 1),
        ("photo_hctrl", 1),
        ("photonames", 1),
        ("photozoomout", 1),
        ("photozoomin", 1),
        ("phot_z_j_out", 4),
        ("phot_z_j_in", 4),
        ("album_pgup", 1),
        ("album_pgdn", 1),
        ("album_itup", 1),
        ("album_itdn", 1),
        ("album_itlf", 1),
        ("album_itrg", 1),
        ("album_ithm", 1),
        ("album_iten", 1),
        ("album_itac", 1),
        ("album_itop", 1),
        ("album_itdl", 1),
        ("camwalk_for", 1),
        ("camwalk_back", 1),
        ("camwalk_righ", 1),
        ("camwalk_left", 1),
        ("camwalk_run", 1),
        ("camwalk_jump", 1),
        ("camwalk_crou", 1),
        ("camwalk_lr", 1),
        ("camwalk_ud", 1),
        ("gearup", 1),
        ("geardown", 1),
        ("gear0", 1),
        ("geardrive", 1),
        ("gearreverse", 1),
        ("gearuphint", 1),
        ("geardownhint", 1),
        ("transemi", 1),
        ("drive", 1),
        ("reverse", 1),
        ("cmirrorsel", 1),
        ("fmirrorsel", 1),
        ("mirroryawl", 1),
        ("mirroryawr", 1),
        ("mirrorpitu", 1),
        ("mirrorpitl", 1),
        ("mirrorreset", 1),
        ("quicksel1", 1),
        ("quicksel2", 1),
        ("quicksel3", 1),
        ("quicksel4", 1),
        ("quicksel5", 1),
        ("quicksel6", 1),
        ("quicksel7", 1),
        ("quicksel8", 1),
        ("mpptt", 1),
        ("replayhidec", 1),
        ("gearsel1on", 1),
        ("gearsel1off", 1),
        ("gearsel1tgl", 1),
        ("gearsel2on", 1),
        ("gearsel2off", 1),
        ("gearsel2tgl", 1),
        ("gear1", 1),
        ("gear2", 1),
        ("gear3", 1),
        ("gear4", 1),
        ("gear5", 1),
        ("gear6", 1),
        ("gear7", 1),
        ("gear8", 1),
        ("gear9", 1),
        ("gear10", 1),
        ("gear11", 1),
        ("gear12", 1),
        ("gear13", 1),
        ("gear14", 1),
        ("gear15", 1),
        ("gear16", 1),
        ("adjuster", 1),
        ("advpage0", 1),
        ("advpage1", 1),
        ("advpage2", 1),
        ("advpage3", 1),
        ("advpage4", 1),
        ("advpagen", 1),
        ("advpagep", 1),
        ("advmouse", 1),
        ("advetamode", 1),
        ("gar_man", 1),
        ("advzoomin", 1),
        ("advzoomout", 1),
        ("assistact1", 1),
        ("assistact2", 1),
        ("assistact3", 1),
        ("assistact4", 1),
        ("assistact5", 1),
        ("adj_seats", 1),
        ("adj_mirrors", 1),
        ("adj_lights", 1),
        ("adj_uimirror", 1),
        ("chat_act", 1),
        ("quick_chat", 1),
        ("cycl_zoom", 1),
        ("name_tags", 1),
        ("headreset", 1),
        ("menustereo", 1)
    ];

    public static IReadOnlyDictionary<string, int> Offsets { get; } = CreateOffsets();

    private static IReadOnlyDictionary<string, int> CreateOffsets()
    {
        var offsets = new Dictionary<string, int>(Fields.Length, StringComparer.Ordinal);
        int offset = 0;
        foreach ((string name, int width) in Fields)
        {
            var member = typeof(ControlVariables).GetField(name,
                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
            Type expected = width == 4 ? typeof(float?) : typeof(bool?);
            if (member?.FieldType != expected || !offsets.TryAdd(name, offset))
                throw new InvalidOperationException($"Unsupported SCSControls ABI v{Version}: {name}.");
            offset += width;
        }
        if (offset != Size || offsets.Count != typeof(ControlVariables).GetFields(
                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).Length
            || offsets[nameof(ControlVariables.gearup)] != GearUpOffset
            || offsets[nameof(ControlVariables.geardown)] != GearDownOffset
            || offsets[nameof(ControlVariables.gear1)] != Gear1Offset)
            throw new InvalidOperationException($"SCSControls ABI v{Version} size or offsets changed.");
        return offsets;
    }
}
